### ISSUE TITLE
Add Support For Database models.ImageField images stored in /media

### ISSUE THREAD

**Issue by 9mido** [andrefarzat/django-webp#3]
In my project, I want to be able to webp images inside /media because Facebook Opengraph and Twitter cards metadata requires filetypes that are not webp. I want my website output to show the webp images while Facebook and Twitter are given the jpeg/png images when not including the webp tag.

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(file)))
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

thumbnail = models.ImageField(blank=True, null=True, max_length=255)

Do something like:

```
<img src="{% webp object.thumbnail.url %}" />
<img src="/media/test.webp" />
```

**Comment by andrefarzat** [comment]
Hello @9mido, this the `object.thumbnail.url` is an external url (not a path to a file in the system) right ? if yes, this lib doesn't work requesting an external source, converting, and serving it. We would need to implement this behaviour

**Comment by 9mido** [comment]
@andrefarzat  It seems Twitter cards and Facebook Opengraph allow .webp files. So I probably do not need to use this feature at all. 

Ah I see what you mean. Yes the object.thumbnail.url would output to 127.0.0.1:8000/media/test.webp.

**Comment by andrefarzat** [comment]
@9mido exactly. It outputs the url to the file, not the path. Therefore it would be possible to __try__ to figure out where the image is (using the `settings.MEDIA_URL` and `settings.MEDIA_ROOT`), but this method isn't error prone.

I will publish a version `2.0.0` with python 3 and django 3 support soon
