### ISSUE TITLE
Apple Safari / IOS Handling

### ISSUE THREAD

**Issue by 9mido** [andrefarzat/django-webp#6]
Is there a way either with this package or in general with django to deal with IOS & safari since it does not support webp as of today? If not, adding an if statement to the template saying if ios/safari then use jpeg/png otherwise use webp. Does this package currently automatically determine if webp is supported on a browser and not use it if it isn't? Otherwise open to other ideas.

Does it check the user agent and deliver a different format? Read the accept headers?

https://caniuse.com/#feat=webp

**Comment by andrefarzat** [comment]
The module check if the client has support or not here:
https://github.com/andrefarzat/django-webp/blob/master/django_webp/context_processors.py#L7
if you have suggestion, please make a PR with the browsers/OS 😸

**Comment by 9mido** [comment]
I am not very good at coding I am just good at finding bugs and making things better with some ideas. Hopefully someone else could though! 

So would adding Safari to that list in the code you linked to solve it? Otherwise, that convert from webp to another format would solve the problem as long as safari is detected. Maybe you could use headers or https://github.com/selwin/django-user_agents ?
