### ISSUE TITLE
Clear cache frequency recommendation?

### ISSUE THREAD

**Issue by 9mido** [andrefarzat/django-webp#8]
How often would you say clearing the cache is needed? What is the best way to run the clean_webp_images? Cron job?

**Comment by andrefarzat** [comment]
I would recommend to clean the cache every time you run a migration, update the code (i.e.: do a release). It should not be necessary too often, for the static images doesn't change that much (right ?)

**Comment by 9mido** [comment]
Ah I see I would not have thought about cleaning it on each migration. But what if you don't use a migration? And just run a site in production that does not get migrations for a long time? Good point it shouldn't have to be that often unless there is a code change. I just wanted to ask to see what your recommendation was.
